:toc: left
== game-box

=== minecraft
Есть великолепный докер образ, который ставит в себя badrock server, так что можно заходить на него и с тедефона и с TV приставки: https://github.com/itzg/docker-minecraft-bedrock-server

Для начала нужно зафризить версию сервера и версию клиента. 

Сервер: через переменную окружения `VERSION`

ПК-клиент: Microsoft Store → Settings → Update apps automatically → Off.

Следующим шагом стоит попробовать поиграть без покупки учетки. Там можно воспользоваться переменной
```
ONLINE_MODE: false # Можно заходить без лицензированной учетки. Читай без покупки игры. Но ни каких админов и читов.
```

Но есть одна проблемка, миры генерятся всратые, а карты надо откуда-нибудь раздобыть.

Для затравки можно попробовать карту https://bedrockminecraft.ru/maps/hide-and-seek/ 
К слову .mcworld это обычный zip архив.

==== first run
после первого запуска можно заметить, что OMV начинате создавать вложенные каталоги от рута, даже если вы выбирали другое в Service - Compose - Settings - Compose Files - Owner

Но это можно обхитрить через ssh: доходите до нужного каталога blabla/appdata и заставляете его делать `chown -R bender:docker-adm minecraft`

==== map-uploader
Но грузить через sftp довольно грустно: нужно сначала залить в /tmp потом переключиться в docker пользователя, потом нашарить нужный каталог, потом разархивировать, потом рестартануть серверный процесс, что бы он подсосал новую карту.

Сценарий можно упростить, поставив web file browser, который будет сохранять файлы сразу от нужного пользователя и группы.
Пошарив по https://www.linuxserver.io/our-images вы не найдете подходящих образов, однако есть один проект использующий https://github.com/filebrowser/filebrowser/blob/master/Dockerfile.s6[s6-overlay] внутри https://hub.docker.com/r/filebrowser/filebrowser/tags?name=s6[докер сборки]: https://github.com/filebrowser/filebrowser

Но образ слишком минималистичный, нужно на его основе будет собрать свой - с архиватором.

После установки открываете http://stone.local:9090/files/ и ищете инстанс бедрок сервера для загрузки карты. 

В случае моего компоуза это будет http://stone.local:9090/files/spider-hides/data/worlds/ 
Там выбираешь "имя" карты `spyder-hides` из компоуза. 
Потом в `data/worlds`.
Там загружаешь архив карты `hide-and-seek.mcworld`. 
В этом каталоге нужно запустить https://github.com/filebrowser/docs/blob/master/configuration/shell-commands.md[веб шелл] нажав ни иконку `<>`.
Далее нужно очистить каталог мира и разархивировать загруженный архив
```
unzip -u hide-and-seek.mcworld -d hide-and-seek
```
Старый мир удалаешь, а разархивированный каталог переименовываешь в имя уровня. В данном случае в `spider-hides`
После этого нужно будет перезапустить контейнер.