:toc: left
:toclevels: 4
== audio-box

=== personal streaming
Работает примерно так же как sptotify, но используется своя библиотека.
Не очень понятно зачем это нужно в наше время, в 2020х объем встроенной памяти на телефонах перевалил за 100 гигов. В 2022 я за сносные деньги взял 256 гиг ROM и просто беру и делаю инкрементальный синк музыки с полным локальных хранением своих несчастных 15 гигов.
Возможно, если переходить на внешний усилитель, соответствующие  наушники и loosles формат, то тогда да, смогу ощутить пользу от персонального стриминга из дома.
Но пока, у меня есть желание просто или слушать любой всратости mp3 c ANC в метро. Или включить радио, что бы какой-нибудь другой мужик думал что там надо включать следующей песне.

Но тем не менее, если очень нужно, можно присмотреться к mstream.

==== mstream
Имеет бесполезную стриничку https://mstream.io/, но проще сразу пройти на https://github.com/IrosTheBeggar/mStream и найти там серверный конфиг https://github.com/linuxserver/docker-mstream#usage и ссылку на приложение на прямую https://github.com/IrosTheBeggar/mstream_music или в магазине https://play.google.com/store/apps/details?id=mstream.music&hl=en_US&gl=US

==== broadcast streaming
В наше время каждый второй обвешивается TV-box'ами и на них то и можно стримить.

===== OwnTone
Но если не нужны фичи раздельных зон, то можно резануть косты и воспользоваться только одним прикладом без мозгодробящих настроек.

Подключаться по http://192.168.2.231:3689 
Отселить его на отдельный mcvlan адрес сразу стоит, что бы потом не было конфликтов с mpd портом 6600 и чем либо еще.

Можно сделать в локалке сетевой плейлист через тот же icecast или даже через https://owntone.github.io/owntone-server/outputs/streaming/ попробовать подключиться к http://192.168.2.321:3689/stream.mp3. Он есть в `OnwTone.m3u`
Но это на любителя, логичнее поставить AirReceiver и явно управлять из приложения.
См для андроид боксов https://4pda.to/forum/index.php?showtopic=1051809&view=findpost&p=126566916


А еще ему можно скормить плейлист онлайн радио, например `Radio Record (AAC 96).m3u8`

===== snapcast
Честный мультирум с зонами, сложный и забористый.
Стоит начать ознакомление с https://habr.com/ru/articles/510544/
и https://github.com/StalkerSVR/snapcast-multiroom
и https://github.com/nolte/docker_compose-audiostation
Там местами хардкод в конфигах, стоит ознакомиться с оригинальным https://github.com/badaix/snapcast#setup-of-audio-playersserver
и с чужими пресетами из

- https://github.com/nolte/docker-snapcast
- https://github.com/sweisgerber/docker-snapcast
- https://github.com/jaedb/snapserver

НО у всего проекта есть одно ограничение, они не работают с tv-box на андроиде, только с RPi и его клонами, так как им нужно очень много из полноценного linux стека. 
Но это обходится с помощью AirReceiver.

====== источники
Если с файлами все понятно, то самой желанной опцией для милинеалов стримить радио или чужие плейлисты. Рестриминг радио вполне умеет owntone. А вот стримить яндекс музыку - не умеет.

Тут потребуется лютая цепочка:

. устанавливается сервер музыки https://docs.mopidy.com/en/latest/installation/
. в него доставляется пакет https://github.com/stffart/mopidy-yamusic
    берет авторизует тебе и сохраняет куку
. и еще один https://mopidy.com/ext/mobile/
    славный UI
. он интегрируется со snapcast https://docs.mopidy.com/en/latest/installation/

=== public streaming
Уже классический стриминг. При этом широковещание так же может по разному интерпретироваться.
Много лет назад вещание было широким в широком смысле этого слова - люди делали интернет радио. Вот прям подтягиваешь сетевой m3u и слушаешь чью-нибудь пиратскую станцию.

Не смотря на то, что в наше время это уже мало актуально, стоит отдать честь таким проектам как https://icecast.org/faq/. Кстати в какой то момент они собрались и сделал мобилный клиент для управления сервером https://coolmic.net. Естественно, страшный как моя бывшая.

В наше время из соображений безопасности не стоит высовывать свой личный приклад наружу за NAT. По этой причине, дальнейшее изучение приостановлено.