---
# name: audio-box
# about: https://github.com/mcgr0g/corcosa
services:

  owntone: # https://owntone.github.io/owntone-server/outputs/streaming/
    container_name: owntone
    image: lscr.io/linuxserver/daapd:latest
    environment:
      PUID: ${PUID2} # redefined global .env in compose .env
      PGID: ${PGID2} # redefined global .env in compose .env
      TZ: ${TZ}
    volumes:
      - ./owntone:/config
      - ${CLOUD1}/Music:/music
      - ${TORRENTS}/music:/torrents
    networks:
      mcvlan_subnet:
        ipv4_address: 192.168.2.231
    restart: unless-stopped

networks: 
  mcvlan_subnet:
    external: true 
    name: elder_ip_subnet_type_c