---
# name: audio-box
# about: https://github.com/mcgr0g/corcosa
services:

  owntone: # https://github.com/owntone/owntone-container
    container_name: owntone
    image: docker.io/owntone/owntone:latest
    environment:
      UID: ${PUID}
      GID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./owntone/configs:/etc/owntone # configs
      - ./owntone/cache:/var/cache/owntone # cache
      - ${CLOUD1}/Music:/srv/media/local
      - ${TORRENTS}/music:/srv/media/torrents
      - ${TORRENTS}/kid/audio:/srv/media/Audiobooks
    networks:
      elder_ip_subnet_type_c:
        ipv4_address: ${IP_ONWTON}
        mac_address: ${MAC_OWMTONE}
    restart: unless-stopped

networks:
  elder_ip_subnet_type_c:
    external: true