=== раскручиваем диски
В системе диски могут быть не примонтированы автоматом, чекни `lsblk -f`.
Монтировать стоит через UI, он там всякие проверки делает и запоминает гуйды дисков.

Диски монтируются с GUID меткой без человечачьего названия, надо сначала узнать кто есть кто через `df -h`, он покажет
```
/dev/sdb1       938G   77M  938G   1% /srv/dev-disk-by-uuid-defeb500-44b5-4d90-90de-5f38c2eb66dd
/dev/sdd1       1.8T   44K  1.7T   1% /srv/dev-disk-by-uuid-b2f9a5d4-ea0f-44d0-9ce9-d72536fbdcb0
/dev/sdc2       3.3T   44K  3.2T   1% /srv/dev-disk-by-uuid-5df3d4ad-0414-4018-a3c9-bd248ee5fa4c
```
И вот теперь становится яcно что

- hdd media: {disk_media}
- hdd media2: {disk_bkp}
- ssd : {disk_os}

Нет понятных меток? Поставь через e2label метки: nox под ссд и kech под шпиндель и станет проще.
```
sudo e2label /dev/sda1 nox
sudo e2label /dev/sdb2 nixMedia
sudo e2label /dev/sdc1 nixBkp
```

=== остановка дисков
Вообще говоря она вредна, потому что частая паркова головок уменьшает срок их жизни. Не даром есть SMART показатель load_cycle_count.
Форумчане поделились заметками

> advanced power management values up to 127 use spin down
> 128-255 are without spin down

и стоит ставить значение 128 в честь этого, если диски поддерживают AMP. Если нет - то пусть крутятся вечно.

==== ssd nox
Для быстрого доступа к дискам виртуалки, собственным поделкам.
Например - в виртуалке можно настроить jupiterlab, а хранилище ноутов ipynb расположить в пробрасываемой в виртуалку файловой системе.
В свою очередь пробрасываемую файловую систему можно указать SMB серверу в качестве цели.
С помощью этой цепочки будет довольно просто извлекать работающие исходники на локальный компьютер для упаковки домашнего задания к сдаче.

Нужно будет в его корне выполнить
```
# под горячие файлы
mkdir kiosk
chown enot:users kiosk
chmod -R 4775 kiosk
```

==== hdd media
будет под торренты и кеш
стоит помнить про целевую структуру каталогов https://wiki.servarr.com/docker-guide#examples необходимых медиа менеджерам
```
# под конфиги всяких образов
mkdir appdata
chown -R bender:docker-adm appdata
chmod -R 4775 appdata

# под свалку
mkdir barn
chown enot:users barn
chmod -R 4775 barn

# под бэкапы
mkdir alcove
chown enot:users alcove
chmod -R 4775 alcove

# под яндекс диск
mkdir yandex
chown enot:users yandex
chmod -R 4755 yandex

# под  загрузки видосики, кеш, в том числе торсерва
mkdir data
chown -R bender:docker-adm data
chmod -R 4755 data
cd data && mkdir media cache

cd torrents
mkdir movies tv 

cd ../ready
mkdir movies tv yt-dlp
```

в итоге структура каталогов будет выглядеть так:
```
tree -dL 4

.
├── appdata
│   ├── copier
│   │   └── cups
│   ├── media-box
│   │   ├── jackettflared
│   │   ├── jackettproxy
│   │   ├── organizr
│   │   ├── plex
│   │   ├── qbittorrent
│   │   ├── radarr
│   │   ├── sonarr
│   │   └── torrserver
│   └── portainer
├── barn
│   ├── devbooks
│   ├── distrib
│   │   └── ide
│   └── knop
├── data
│   ├── cache
│   └── media
│       ├── ready
│       │   ├── movies
│       │   └── tv
│       ├── torrents
│       │   ├── abook
│       │   ├── blackhole
│       │   ├── book
│       │   ├── downloads
│       │   ├── history
│       │   ├── kid
│       │   ├── movies
│       │   ├── music
│       │   ├── serial
│       │   ├── soft
│       │   └── webinar
│       └── ytb
│           ├── blues
│           ├── music shows
│           └── webinar
├── lost+found [error opening dir]
├── www-data
│   └── dummy
│       └── html
└── yandex
    ├── Music
    ├── blackhole
    └── project
        └── corcosa
```

==== livehacks
Ходить по таким дискам достаточно долго и нудно, даже с автокомплитом.
Для таких вещей и придумали алиасы. Можно сделать `cd ~ && vim .bash_aliases` и подкинуть в него
```
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../../'
alias path='echo -e ${PATH//:/\\n}'
alias nixmedia='cd /srv/dev-disk-by-uuid-5df3d4ad-0414-4018-a3c9-bd248ee5fa4c'
alias nixbkp='cd /srv/dev-disk-by-uuid-b2f9a5d4-ea0f-44d0-9ce9-d72536fbdcb0'
```
a затем применить `source ~/.bash_aliases`
