---
version: '3'
services:
  watchtower:
  # https://containrrr.dev/watchtower/arguments/
    image: containrrr/watchtower
    hostname: stone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      # - WATCHTOWER_HTTP_API_UPDATE=true
      # - WATCHTOWER_HTTP_API_TOKEN=026314c0-0dad-46e4-9104-6fb32d179e1b
      # curl -H "Authorization: Bearer 026314c0-0dad-46e4-9104-6fb32d179e1b" 192.168.2.10:9009/v1/update
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=stone
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=ololo@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=ololo@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=blabla
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=enot@gmail.com
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=86400
    ports:
      - 9009:8080 # https://containrrr.dev/watchtower/http-api-mode/
    restart: unless-stopped
