=== Сеть
Вообще дебиан поделки надо ставить с подключенной витой парой. Занятно, что CUI installer видел что сети нет и ругался, что не может смонтировать cd-rom.

А если есть WiFi карта?
После изучения NetworkManager можно заметить, что есть только проводной интерфейс. Есть даже устройство, и дровишки от интела iwlwifi-8265-20.ucode. Но почему то интерфейс к железу не был создан. Форумы подсказывали изучать бут-логи
```
dmesg | grep iwl
```
Это частая проблема у дуалбутчиков, руткоз "на винде вы не отключили 'быструю загрузку' по этому она зажала wifi карту под себя для функции WakeUpOnLan ".

В lan у большинства soho роутеров используется подсеть 192.168 (типа С). 
Третий байт будет кастомным: 192.168.2. Пригодится, если к своей сети потребуется присоединить дефолтную SOHO сесть 192.168.1 или менее распространненую 192.168.0.
Красоты ради, для физических устройств младшие адреса стоит закрепить за сетевыми устройствами: роутеры, точки доступа, приставки.
Для контейнеров будет выделены старшие адреса: 192.168.1.225 - 192.168.1.254.
29 macvlan интерфейсов хватит с головой. Если не хватает - вы делаете что то свое большое и уже умеете гуглить

Калькулятор https://www.subnet-calculator.com/[подсести] помогает высчитать, 
что подходящая маска 192.168.2.224/27 (255.255.255.224)

Получить имя сетевого интерфейса можно командой `ip a`, у меня это enp3s0.
По мотивам https://forum.openmediavault.org/index.php?thread/39510-how-to-use-the-openmediavault-kvm-plugin/[\[How-To\] Use the Openmediavault-KVM plugin], сразу после установки стоит сменить сетевой интерфейс с дравера карточки на бридж br0, в который нужно добавить только карточку enp3s0
