:sectnums:
:toc: left
== OpenMediaVault
Так вышло, что обещания в спеках подогнать рабочий релиз в 2021q4 не означает, что в конце Декабря - это действительно будет.

=== install
Рабочий вариант: добавить их репозитарий и ключи, скачать кастомный скрипт установки и выкинуть из него проверку на Desktop Env.
https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/install#L30
У меня прокатило, не знаю что будет через 2 года.

=== config
Есть несколько нюансов:

- пользаков стоит создавать не скриптом, а в UI
- при создании они будут добавляться в группу users сами. Но нужно будет самостоятельно добавить их в группу ssh
- самопальным скриптом конфигурить sshd бесполезно, скрипты UI беспощадно перезатирают. 
- Если отключил парольную авторизацию в ssh, нужно добавить всем пользакам группу ssh

==== конфиги шары
Надо начинать с конфигов ФС: корректно создать каталоги и права доступа к ним

Из под UI будут такие
https://openmediavault.readthedocs.io/en/5.x/administration/access_rights_management.html#id3[варианты создания и доступа к каталогам].
Немного http://mcgrog.blogspot.com/2013/10/blog-post_28.html[личных заметок] на эту тему

Есть определенные прикол с веб интерфейсом:
если диск пустой, и через UI содается структура вида /DEVICE/media/video, то права у нее будут root:root.

Да, можно в GUI настроить ACL, что бы поменять группу у каталога, но изменения будут применены только к оконечному каталогу. А родительский (/DEVICE/media) все еще будет с правами root:root. Делайте руками, вот что должно быть видно
```
enot@stone:/srv/dev-disk-by-uuid-bd72f3d3-c890-4315-b2e2-a15b15df1564/$ ls -la
total 16
drwxrws---+ 4 root users 4096 Dec 30 13:06 .
drwxr-xr-x  4 root root  4096 Dec 30 12:34 ..
drwxrws---+ 2 enot users 4096 Dec 30 13:06 music
drwxrws---+ 2 root users 4096 Dec 30 12:35 video
```

И теперь можно пробросить музыку из Диска
`ln -s /home/enot/Yandex.Disk/Music/ /srv/dev-disk-by-uuid-bd72f3d3-c890-4315-b2e2-a15b15df1564/media/music`

=== чек лист
После активации самбы стоит проверить версию протокола на сервере
```
samba --version
cat /etc/samba/smb.conf
```

и сделать проверочки на win клиенте:
`dir \\STONE\barn`
а потом из под админа `Get-SmbConnection`

если еще не робит, то вот топ проблем с форума, в которые наступил сам.

==== проблема 1 - нет доступа пользователю
нужно настроить не только ACL на каталог, но и привелегии пользователю - проставить галочки на опции чтения и изменения. Они не связаны с правами доступа в каталог на ФС, они выдают права в контексте прав самбы

==== проблема 2 - сменили пароль пользователю коряво
или через ssh или как то еще, но не через webUI. Надо было менять через веб морду - тогда еще и самбе пароль поменяет. Самому руками можно сделать через `smbpasswd stub`

если система сообщает что не может найти такого пользователя `Failed to find entry for user stub`, хотя он есть в OS, 
то нужно добавить пользователя в базу cамбы `smbpasswd -a stub`

==== проблема 3 - винда залипла
И не пускает, хотя на смарте X-Plore находит шару и пускает.
Нужно на win запустить Credentional Manager, подулалять записи напоминающие самбашару и перезапуститься.
перезапуститься важно, у меня без этого залипала.

