:sectnums:
:toc: left
== intro
Мой сетап:
CPU: i3-4130
RAM: 2*8 800 MHz DDR3
ROM: Samsung 860 Evo 256Gb
OS: Debian 11 (bullseye)
name: stone.lan

Почему не RPi? Потому что это куцее дерьмо для школьников.

Первое ядро отъест ОС, omv, докер поделки и транскодирование на лету
Второе ядро пойдет под виртуализацию, как поделок так и для hass.io. Существенно проще сделать именно так и не иметь проблем по обеспечению сетевой связности (или изолированности) контейнеров для кишков умного дома. Да и еще зависимости отслеживать не нужно.

Может показаться, что запас оперативки избыточен. 
В принкипе это верно, если использовать докер образы и штатные планины.
folder2ram подъедает не так много памяти. 
qbittorrent в отличие от utorrent имеет другую стратегию утилизации памаяти и дисков и ему нужно совсем не много.
В итоге бы хватило 4 Gb. Но в моих планах: обновить процессор и крутить 3 виртуалки с аллокацией ram - по 4 Gb.

Нормальная, хоть и старая, мамка дает 2 sata2 порта и 2 sata3. И они прекрасно распределяются между 2мя ssd (под ось и vm), и 2мя hdd под медиа и бэкапы.
Сетап жирноват, можно было бы обойтись и 1 ssd + 1 hdd. Однако, диски имеют обыкновение сыпаться внезапно, а когда все уже в корпусе и подключено - сил и нервов уходит значительно меньше.

Нормальные USB порты дадут возможность заливать фильмы на внешний ssd в кармашке, просто воткнув его.

Как бы плохо не отзывались о морально устаревшем сетапе, он не заставит грустить еще 10 лет. Если сборка дотянет до юбилея в 20 лет, это действительно будет круто.

=== дистрибутив ОС
Не стоит использовать урезанные исошники на 300 метров. Бери с DVD и проприетарным софтом через торренты. 
У них там пьяная навигация по сайту, сложно попасть на https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/archive/10.11.0+nonfree/amd64/iso-dvd/
или
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/11.2.0-live+nonfree/amd64/bt-hybrid/
Там дальше можно прогуляться по каталогу и выбрать нужную тебе сборку.

=== сама установка
Будет простой, у кого есть диск, который могут выделить целиком под систему.
Но монитор с клавиатурой отключать еще рано.

Для дуалбутчиков, нужно сначала из под Live Ubuntu разметить диски и запомнить.

Потом под Debian Installer (например debian-live-11.2.0-amd64-standard+nonfree.iso) ставить систему.
OMV installer не умеет делать и даже видеть отдельные партиции, только диск https://openmediavault.readthedocs.io/en/latest/installation/via_iso.html#installer[целиком]

Но есть неприятный нюанс: если пользоваться debian installer без DE: после установки несвободного софта, остется отмета на cdrom "как на репозитарии пакетов". Так что в `cat /etc/apt/sources.list.save` нужно будет закомментировать строку вида
```
deb cdrom:[Debian GNU/Linux 10.11.0 _Buster_ - Unofficial amd64 DVD Binary-1 with firmware 20211009-16:12]/ buster contrib main non-free
```

ну и по умолчанию пользователя нет в судоерах, нужно попросить добавить `gpasswd -а enot sudo`

== конфигурация основных параметров ОС
include::net.adoc[]

include::disks.adoc[]
