:sectnums:
:toc: left
== prerequisites
Для начала нужно настроить на хосте ОС и среду исполнения

=== дистрибутив ОС
прежде всего не нужно качать сраный урезанные исошники на 300 метров. Бери с DVD и проприетарным софтом через торренты. У них там пьяная навигация по сайту, сложно попасть на https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/
или
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/archive/10.11.0+nonfree/amd64/iso-dvd/
Там дальше можно прогуляться по каталогу файлов и для 11 версии набрести на
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/11.1.0-live+nonfree/amd64/bt-hybrid/

=== сама установка
Довольно приятно ее выполнять из под GUI. Хотя бы потому что там есть страшненький разметчик дисков. Пригодится, что бы дуал бутом выжила винда.
Я ставил на древний SSD на остаток в 90 ГБ, хватает с головой. Дальше будет перенос тяжелых вещей на примонтированные диски.
Но есть неприятный нюанс, если пользоваться установщиком без KDE: после установки несвободного софта, остется отмета на cdrom "как на репозитарии пакетов". Так что в `cat /etc/apt/sources.list.save` нужно будет  закомментить строку
```
deb cdrom:[Debian GNU/Linux 10.11.0 _Buster_ - Unofficial amd64 DVD Binary-1 with firmware 20211009-16:12]/ buster contrib main non-free
```

== конфигурация ОС
=== Сеть
Вообще дебиан поделки надо ставить с подключенной витой парой. Я так безуспешно пытался запустить iso сборку под CD носители. И этот гад видел что сети нет и ругался, что не может смонтировать cd-rom. Но у меня был отдельный прикол, что сеть не получала DHCP конфигурацию, с рабочей витухой и роутером. Именно по этому стоит медленно и печально качать жирные сборки с хилых серверов сочувствующих.

А если есть WiFi карта?
После изучения NetworkManager можно заметить, что есть только проводной интерфейс. Есть даже устройство, и дровишки от интела iwlwifi-8265-20.ucode. Но почему то интерфейс к железу не был создан. Форумы подсказывали изучать бут-логи
```
dmesg | grep iwl
```
Моя ошибка там гуглилась плохо, ближе к концу первой страницы гугла дуалбутчик описал руткоз как "на винде вы не отключили 'быструю загрузку' по этому она зажала wifi карту под себя для функции WakeUpOnLan ". Поржал, Попробовал, зарабтало.

=== диски
диски монтируются с GUID меткой без человечачьего названия, надо сначала узнать кто есть кто через `df -h`, он покажет
```
/dev/sdb1          938G          77M  938G            1% /srv/dev-disk-by-uuid-defeb500-44b5-4d90-90de-5f38c2eb66dd
/dev/sda2           96M          30M   67M           31% /boot/efi
/dev/sdc3          1,4T          77M  1,3T            1% /srv/dev-disk-by-uuid-bd72f3d3-c890-4315-b2e2-a15b15df1564
```
И вот теперь становится яcно что

- hdd: {disk_hdd}
- ssh: {disk_hdd}

Нет понятных меток? Постави через e2label метки nox и  kech
```
sudo e2label /dev/sdb1 nox
sudo e2label /dev/sdc3 kech
```

==== ssd 
Для докеров и поделок с виртуальными окружениями.
Нужно будет в его корне выполнить
```
mkdir docker-res

# под горячие файлы
mkdir kiosk
chown enot:users kiosk
chmod -R 4775 kiosk
```

==== hdd
будет под торренты и кеш
```
# под обычные торренты
mkdir torrents
chown enot:users torrents
chmod -R 4775 torrents

# под видосики
mkdir video
chown enot:users video
chmod -R 4775 video

# под свалку
mkdir barn
chown enot:users barn
chmod -R 4775 barn

# под яндекс, с урезанными правами
mkdir yndx
chown enot:users yndx
chmod -R 4755 yndx
```
