:toc: left
:toclevels: 4

=== Plex
Если хочется начинать просмотр на одном телеке, а продожить на другом - тут будет удобнее или с плексом и ли с Jellyfin. Выбор сервера был https://hub.docker.com/r/plexinc/pms-docker[очевиден], там больше переменных окружения, которые можно пробросить внутрь контейнера.

==== Порты и сеть
Лучше иметь нормальный dlna отдельно от плекса. Хотя бы на стадии экспериментов.
Так же стоит помнить, что все домино скрпитов может плохо работать просто из-за jackett'а. 
Бывает банально быстрее на телефоне открыть письмо в гмыле, протыкать ссылки и поставить на скачивание серию. 
При таком юзкейсе кина в plex не будет и его dlna обследовать бессмысленно. По этому у меня на plex'е выключен dlna, но включен на хост OS.
И так на хосте стоит miniDLNA, 1900 порт был занят. Что бы избежать коллизии порторв на стадии запуска, стоит использовать бридж сеть.

Если вы решили не пробрасывать порты за NAT и не тюнить удаленный доступ, то на внешний сервер приклад отправит тот IP который ему будет виден из бриджа - 172.18.0.x. По этому стоит заполнить `ADVERTISE_IP` адресом хост системы.
Без этого конфига щmbi, overseerr да и остальные смогут авторизоваться на wan сервере, но не сможет получить параметры lan подключения. А вещание через wan ретрансляторы - такая себе идея: будет понижение качества до 480p.

==== Авторизация
Придется немного пошелудить руками.
Зайдите на https://plex.tv/devices.xml и изучите исходник страницы. Нужный вам элемент вы без труда найдете глазами
`<Device name="Ombi" product="Ombi" productVersion="3" platform="Web" platformVersion="" device="Ombi" ...`
Берите тэги token и id подставляйте их в `plex authorization token` и в `machine identifier`.
Порт - классический 32400.

Между делом, в инфраструктуре плекса могут падать и wan сервера. И если это не предусмотреть, то на lan сервере в такие моменты не выйдет https://www.reddit.com/r/PleX/comments/we0xtd/comment/iilnizm/?utm_source=share&utm_medium=web2x&context=3[даже авторизоваться].
По этому в `ALLOWED_NETWORKS` следует добавить зафиксировнный на роутере ip ноута и "взрослого телевизора".

==== Транскодирование
ТВ приставки нынче заряженные и умеют играть DD+ звук, но Плекс может спотыкаться об дороги ac3 и eac3: или запускать принудительное транскодирование или тупо молчать.
На тему проброса ac3 звука народ давно https://forums.plex.tv/t/movies-with-eac3-5-1-codec-dosnt-play/513263/17[костылит]. 
Но у меня не завелось. Мануал по https://www.plexopedia.com/plex-media-server/general/client-profiles/[клиентским профилям] помог сделать такой профиль

[source,xml]
----
include::Android.xml[]
----
:toc: left
Измененные строки подсвечены комментом ``

ТВ приставки нынче заряженные и умеют играть DD+ звук, но Android Plex app может спотыкаться об дороги ac3 и eac3: или запускать принудительное транскодирование или тупо молчать.


Что бы подсунуть его в кишки докера, нужно немного повозиться: сначала выковырять все из контейнера, а потом уже монтировать как внешний том.
В этом поможет link:fixtureProfile.sh[фикстура], запускать от sudo.
