# name: plex
# about: https://github.com/mcgr0g/corcosa
services:
  plex-server: # https://github.com/plexinc/pms-docker
    image: lscr.io/linuxserver/plex:latest # freeze version https://hub.docker.com/r/plexinc/pms-docker/tags/
    container_name: plex
    hostname: stone
    environment:
      TZ: ${TZ} # timezone, defined in .env
      PLEX_UID: ${PUID} # default user id, defined in .env
      PUID: ${PUID}
      PLEX_GID: ${PGID} # default group id, defined in .env
      PGID: ${PGID}
      HOSTNAME: stone
      PLEX_CLAIM: claim-bdA_spLWN1Un4_hMnPD5
      ADVERTISE_IP: http://${IP_PLEX}:32400
      ALLOWED_NETWORKS: ${SUBNET_IP}/${SUBNETM_FULL}
      VERSION: docker
      http_proxy: http://192.168.2.235:20171
    volumes:
      - ./plex/db:/config # plex database
      - ./plex/profiles:/usr/lib/plexmediaserver/Resources/Profiles # для подхачивания транскодирования
      - ${ROOT}/cache/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/media:/media # media library
      - ${DONWL2}:/webinars2
      - ${CLOUD1}/Music:/music-lcl # music library
      - ${CLIPS}:/clips # сохраненки из ютуба
    devices:
      - /dev/dri:/dev/dri # https://github.com/plexinc/pms-docker#intel-quick-sync-hardware-transcoding-support
    ports:
      - 32400:32400/tcp # main
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      elder_ip_subnet_type_c:
        ipv4_address: ${IP_PLEX}
        mac_address: ${MAC_PLEX}
    restart: unless-stopped

networks:
  elder_ip_subnet_type_c:
    external: true
