---
# name: video-box
# about: https://github.com/mcgr0g/corcosa
services:

  torproxy:
    container_name: torproxy
    image: mcgr0g/talpa-altaica:latest
    environment:
      EXCLUDE_NODE: '{RU},{UA},{AM},{KG},{BY}'
    ports: 
      - 8888:8888
      - 8119:8889
      - 9050:9050/tcp
    restart: unless-stopped

  jackettproxy: # версия сервиса для работы через медленный torproxy, без flaresolverr
    container_name: jackettproxy
    image: linuxserver/jackett:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jackettproxy:/config
      - ${ROOT}/media/torrents/blackhole:/downloads # place where to put .torrent files for manual download
    ports:
      - 9117:9117
    networks:
      - jumper2kamartaj
    restart: unless-stopped

  jackettflared: # версия сервиса для работы через медленный torproxy, и с flaresolverr
    container_name: jackettflared
    image: linuxserver/jackett:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jackettflared:/config
      - ${ROOT}/media/torrents/blackhole:/downloads # place where to put .torrent files for manual download
    ports:
      - 9118:9117
    networks:
      - jumper2kamartaj
    restart: unless-stopped
  
  flaresolverr: # кривая балалайка для обхода cdn. Не умеет в proxy и решать капчи.
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: ${TZ}
    ports:
      - 8191:8191
    networks:
      - jumper2kamartaj
    restart: unless-stopped

  qbittorrent: # https://github.com/linuxserver/docker-qbittorrent
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      WEBUI_PORT: 8080
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ./qbittorrent:/config
      - ${ROOT}/media:/media
    ports:
      - 6881:6881 # tcp connection port
      - 8080:8080 # http gui
      - 9001:9001 # tracker port
    networks:
      - jumper2kamartaj
    restart: unless-stopped

  sonarr: # сериалы
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - ${ROOT}/media:/media # both downloads & media folders folder
    ports:
      - 8989:8989
    network_mode: host
    restart: unless-stopped

  radarr: # кино
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      PUID: ${PUID} # default user id, defined in .env
      PGID: ${PGID} # default group id, defined in .env
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config # config files
      - ${ROOT}/media:/media # both downloads & media folders folder
    ports:
      - 7878:7878
    networks:
      - jumper2kamartaj
    restart: unless-stopped

networks:
  jumper2kamartaj:
    external: true