:toc: left
:toclevels: 4
== video-box

=== references
Наработки взяты из мануалов

- https://github.com/sebgl/htpc-download-box
- https://creio.github.io/media-server/
- https://connect.smartliving.ru/profile/225/blog/ustanovka-i-nastroyka-sonarr-radarr-qbittorrent-jackett-torproxy-v-docker.html
- https://habr.com/ru/post/428992/

[[qbit]]
=== torrent client
Театр начинается именно с этой вешалки https://github.com/linuxserver/docker-qbittorrent
(хотя есть и https://hotio.dev/containers/qbittorrent/[альтернативные] сборки )

Не смотря на то, что мануалы сонара рекомендуют монировать контейнер как `${ROOT}/media/torrents:/media/torrents`, рекомендую монтировать как `${ROOT}/media:/media`. Причина простая: сонар, да и радар плохо умеет сам искать и сопоставлять русские заголовки. Особенно плохо ему делается при попытках найти какой-нибудь весь пак старого сериала. Тогда приходится руками выкачивать в каталог сонара. Тут то и нужен доступ в его каталоги.

Все остальное для штатного использования рекомендуется выстраивать относительно `/media/torrents/`.

Каталог для мониторинга торрент файлов стоит назначить как `/media/torrents/blackhole`. В него можно настроить перекладывание .torrent файлов по крону.

Для отладки смотрим что происходит внутри `sudo docker exec -it qbittorrent bash`

==== Категории
Например, скачивание по умолчанию без категорий можно назначить скачивание в `/media/torrents/downloads`
Можно задать "пустую категорию", тогда скачивание пойдет в `/media/torrents/downloads/categoryName`.

Однако удобнее всего пользоваться подготовленными категориями вида
moovie = '/media/torrents/movies'
serial = '/media/torrents/serial'
radarr = '/media/torrents/movies'
sonarr = '/media/torrents/serial'

Хак с отдельной категорией для радара и сонара упрощает жизнь в реалиях отчечественных трекеров. 
В PVR можно настроить категорию для скачивания и пост категорию для готового фильма. При этом фильм не будет считаться готовым, если PVR не смог его сграбить автоматом. А один чудный трекер постоянно отдает в названии торрента "rutor.info" вместо имени темы или названия файла. И radarr имено так его и показыват в своем интерфейс для импорта контента. По этому каждый раз в интерфейсе qbit приходится править название торрента по имени файлу руками. И гораздо проще найти это непотребство фильтранувшись по категории.

==== анонсеры
Стоит сразу же добавить список ретрекеров https://github.com/ngosang/trackerslist
в ⚙ → BitTorrent → Automatically add these trackers to new downloads

для проверки аптайма анонсера можно воспользоваться https://newtrackon.com/

Скорее всего большая часть будет заблокирована, стоит использовать https://github.com/bluet/proxybroker2

==== SSL и магнит
Если очень хочется по одному простому клику добавлять торренты, это можно, но геморрно.
в UI зарегистрировать веб приложение как обработчик магнет ссылок можно в 1 клик, проблема только в том, что приклад требует выпуск SSL сертификатов в обязательном порядке.
Есть 2 варианта: выпустить из консоли или из под UI: https://docs.openmediavault.org/en/latest/administration/general/certificates.html#ssl-secure-socket-layer

Правда потом все равно потребуется из под консоли скопировать или сделать симлинк на сертификаты.
Я решил выпустить из UI, что бы можно было легко проверять как долго осталось до истечения серта и мне пришлось так раскидать файлы
```
cd /srv/dev-disk-by-uuid-5df3d4ad-0414-4018-a3c9-bd248ee5fa4c/appdata/video-box/qbittorrent
mkdir ssl && cd ssl
cp /etc/ssl/private/openmediavault-9a1df8c9-b47b-48f8-a42d-42c60a75d5ae.key privatekey
cp /etc/ssl/certs/openmediavault-9a1df8c9-b47b-48f8-a42d-42c60a75d5ae.crt cert
```
и после в конфигах qgit можно их прописывать в ⚙ → Web UI → Use HTTPS instead of HTTP:
Certificate: `/config/ssl/cert`
Key: `/config/ssl/privatekey`

IMPORTANT: После применения настроек по http зайти уже не получится, только по https.

=== TorrServer 
Проект https://github.com/YouROK/TorrServer работает даже на android боксах. 
Если телеков несколько, а сервер один, можно сэкономить на wifi траффике, стримить телекам контент по dlna.
Если вы собираете проект под amd64, стоит нацеливать хранение кеша на пзу в `/opt/ts/torrents/`. Этот каталог пробрасывается в хост систему. И проверьте что он создается именно там, запустим торрент и провалившись в контейнер
```
sudo docker exec -it torrserver sh
ls -la /opt/ts/
```
При этом там только кэш, который ничем сторонним прочитать нельзя, так что располагать его в структуре smb или dlna шары - бессмысленно.

Если вы зачем то делаете это на rpi, то взаимодействие с диском у вас будет так себе, нужно оставить дефолтный конфиг с записью в ram.

Там же в конфигах можно включить опцию dlna шары и она будет стримить выбранный торрент файл.
Сделав этот выбор, контейнер придется перенести в сеть маклана на отдельный ip, что бы не было коллизии портов с baremetal dlna сервером. 

Зачем? Онлайн стриминг это конечно хорошо, но локальне файлы должны быть доступны всегда и по самому бородатому протоколу. 


=== torproxy
Потребуется для доступа к заблокированному контенту, torrent трекерам, ретрекерам, а нынче еще и для доступа к серверам sonarr и radarr
Есть классные сборки образов

- https://github.com/binfalse/docker-tor
- https://github.com/datawookie/docker-tor-privoxy

но ни в одной нет проброса env'а ExcludeExitNodes.
Пришлось https://github.com/mcgr0g/tor-privoxy[подшаманить] самому.

Главная опция: ExcludeExitNodes {RU},{UA},{AM},{KG},{BY}

Бесполезно использовать для торрент траффика, для этого уже нужно покупать vpn.
В конце 2024 стал бесполезен из-за блокировки cloudflare и не возможности проводить domain fronting

=== organizers
И sonarr и radarr нужно скормить одни и теже индексаторы, одни и теже качалки, каталоги.
Об этом всем подробнее в мануале https://wiki.servarr.com/docker-guide#sonarr-radarr-and-lidarr
И в процессе постоянного тюнинга потребуется часто переключаться между приложениями.
А  можно настроить дашборт с jump-кнопками и текущими статусами очередей задач. Для этого пригодится https://github.com/organizr/docker-organizr

Установка не замысловатая. Настраивается по мере ввода в эксплуатацию нового приклада.

[[torrent-indexer]]
=== Jackett
Он не сможет работать в наших реалиях без flaresolverr и tor (или VPN). 
При этом скорость взаимодействия будет очень медленной. Так что для первичного запуска стоит воспользоваться torproxy, а потом тюнить конфиги для более быстрого соединения через vpn туннель.
При дефолтных настройках контейнеров,

```docker
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      PUID: ${PUID} # default user id, defined in .env
      PGID: ${PGID} # default group id, defined in .env
      TZ: ${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/configs/jackett:/config # config files
      - ${ROOT}/yandex/blackhole:/downloads # place where to put .torrent files for manual download
    ports:
      - 9117:9117
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: ${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped 
```
нужно в UI прописать 

- Proxy type: SOCKS5 // подключение на прямую к tor клиенту сети
- Proxy URL: `proxyd` // при взаимодействии в докер сети за бриджом хосты будут резолвиться по имени контейнера
- Proxy port: `20170` # proxy direct port
- FlareSolverr API URL: `http://flaresolverr:8191`
- FlareSolverr Max Timeout (ms): `105000` из-за неторопливости tor

После добавления любимых трекеров стоит их протестировать и поискать какие-нибудь новинки. Если все отлично, то на этом стадия первичного запуска считается завершенной.

==== The cookies provided by FlareSolverr are not valid
Довольно старая https://github.com/FlareSolverr/FlareSolverr/issues/89[проблема], на самом деле, поставщик кук это jackett и него есть попытки описать способы https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work[преодоления] проблемы.

=== vpn client
При использовании платного VPN следует помнить, что jackett и flaresolverr должны быть за одним ip, использовать одни и теже куки, без ipv6
https://github.com/FlareSolverr/FlareSolverr/issues/664#issuecomment-1374505316[про куки для Cloudflare]
https://github.com/FlareSolverr/FlareSolverr/issues/89#issuecomment-1004753308[про ipv6]

По этой причине конфиг vpn должен выглядеть примерно так
```docker
  ovpnc:
    container_name: ovpnc
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    ports:
      - 8191:8191 # хак с высовыванием порта для flaresolverr
      - 9117:9117 # хак с высовыванием порта для jackett
    environment:
      TZ: ${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/configs/ovpnc:/vpn # OpenVPN configuration
    devices:
      - "/dev/net/tun:/dev/net/tun"

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      PUID: ${PUID} # default user id, defined in .env
      PGID: ${PGID} # default group id, defined in .env
      TZ: ${TZ} # timezone, defined in .env
    network_mode: service:ovpnc # run on the ovpnc network

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:ovpnc # run on the ovpnc network
```
Кстати, это один из немногих ментейнеров, которые сразу в мануале указали не только как присоединить сетевой стек vpn клиента к подопытному контейнеру приклада, но и как сделать реверс-проксирование.
К сожалению, запуск с платным vpn не был аппробирован. И не будет их всех побанили.

==== antizapret
Не работает


=== radarr
качает фильмы
сначала надо сделать приседание с регистрацией и получения идентификатора своего листа к просмотру

[[list-id]]
==== imdb 
Важно айдишник, начинающийся на ur - это id пользователя.
id списка начинается на ul. Как его получить?
Идете на свой профиль вида `https://www.imdb.com/user/ur123/watchlist`
На странице ищите `Export this list`
Под текстом будет ссылка, содержащая id листа.

Дальше надо скормить идентификатор серверу.

==== Root Folders
в Settings  → Root Folders → Path указываете путь вида `/media/ready/movies`
Это каталог в проброшенном volume в докер. Будет использоваться для красивого раскладывания фильмов, описания и аротов, что бы их скушал plex или jellyfin
Если использовалась структура каталогов из этого проекта, то раскладывание будет осуществляться с помощью хардлинков, нацеленных на каталог qbittorent.

==== Profiles
Нужно в каждом профиле поставить русский язык

==== General
в Settings → General → Proxy указываете параметры подключения к контейнеру с тор. Иначе не заработает.
В Settings → General → Proxy → Ignored Addresses укуазываешь
`localhost, jackett, jackettflared, qbittorrent, *.lan, *.local, 192.168.2.*`

==== Download Clients
в Settings → Download Clients добавляте qBittorrent с параметрами

- Host: qbittorrent
- Port: 8080
- Username: <ваш сконфигуренный пользователь в клиенте>
- Password
- Category: radarr (ее уже настроили в разделе [<<qbit>>], о ней подборнее будет ниже)

==== Lists
в Settings → Lists добавляте новый список с типом `IMDb List`. Там конфигурируетe

- Quality Profile: например в 1080p
- Folder: /media/ready/moovies
- List/User ID: ваш список просмотра из [<<list-id>>]

Если немного подождать или попинать интерфес в Moovies → Update all, то
сервер через torproxy пойдет сначала в imdb и потом создаст каталоги и метаданные фильмов

===== Indexers
в Settings → Indexers добавляете torrent индексы c стипом `Torznab`
и для каждого настроенного торрент трекера/форума в [<<torrent-indexer>>] копируете tornzab и api-key и вставляете в модалке
- URL: `http://jackettflared:9117/api/v2.0/indexers/rutor/results/torznab/`
- API Key: ну вы поняли

====== Categories
Следует выделить только те категории с трекера, которые вам интересны. Например на рутрекере есть куча разделов под всякую музыку, софт и прочее барахло, которое нет смысла процессить.

Пример тэгов (не системных для всего радара, а только для индексатора), которые были полезны мне

[%autowidth%header,separator=|]
|===
| тэг | назначение 

| 2040
| Movies/HD

| 2045
| Movies/UHD

| 2070
| Movies/DVD

| 101457
| UHD Video

| 102294
| UHDTV

| 100004
| Мультфильмы

| 100313
| Зарубежное кино (HD Video)

| 100119
| Зарубежные сериалы (UHD Video)

| 101803
| Новинки и сериалы в стадии показа (HD Video)

| 102366
| Зарубежные сериалы (HD Video)

| 100920
| Русские сериалы (DVD Video)

| 100081
| Русские сериалы (HD Video)

| 100312
| Наше кино (HD Video)

| 102164
| BBC, Discovery, National Geographic, History Channel (HD Video)

|===

Сам процессинг при этом может иногда сыпать ошибками в System → Events.
Это связано с тем, что torproxy переключается между выходными нодами и переключение может совпасть с моментом опроса новинок.

===== manual import
У многих не ищутся фильмы из-за кривых локализованных заголовковов фильмов 
или из-за разных дат релиза в мире (был один год), и в стране релиза (часто следующий).

И при том разработчики умышленно не дают пофиксить заголовки, говорят идти на tvdb и фиксить там.
Я пробовал, это так не работает.
Но есть обходной маневр: руками через jacket найти нужный фильм, скачать torrent файл, а при добавлении его в <<qbit>> поставить категорию radarr.
Тогда сервис заметит его в попытается сграбить. Даже если у него не получится, то можно ему подмогнуть через Grab selected

===== повышенная утилизация дисков.
По умолчанию radarr использует тактику создания хардлинков вместо копирования. Но он может переключиться на копирование, если файл заблокирован каким либо процессом, например сидированием. При этом эти господа не позаботились функцией остановкой (паузой) торрекнта, даже при наличии API и предлагают руками его останавливать, импортировать закачаное и потом включать.

в UI
/dev/sde2 nixMedia Available:1.31 TiB Used: 1.80 TiB

в консли df -h
Filesystem      Size  Used Avail Use%
/dev/sde2       3.3T  1.9T  1.4T  58%
/dev/sde2       3439013 1888078   1376172  58%

в консли du -sh на корне диска
1.9T

После , тяжелого файла, импорта с отключенными торрентарми,  показатели не изменятся, а хардлинк будет установлен: чило 2 напротив .mkv файла говорит об этом.
```
ls -la
total 57912108
drwxrwxr-x+   2 bender docker-adm        4096 Dec 25 02:18  .
drwsrwxr-x+ 107 bender docker-adm       12288 Dec 25 02:17  ..
-rwxrwxr-x+   2 bender docker-adm 59300739524 Mar 25  2022 'Joker (2019) Remux-2160p.mkv'
-rw-rw-r--+   1 bender docker-adm        8690 Dec 25 02:18 'Joker (2019) Remux-2160p.nfo'
-rw-rw-r--+   1 bender docker-adm      299647 Dec 25 02:17  fanart.jpg
-rw-rw-r--+   1 bender docker-adm      815122 Dec 25 02:17  poster.jpg

```

=== sonarr
Качает сериалы. Настраивается аналогично, но сериалы добавляются руками, а не через какой-нибудь внешний список к просмотру.

==== особенности докер сети
по какой то неведомой причине эти славные ребята не могут сделать нормальное проксирвание вызвовов и ловиш ошибку с эксепшеном

----
blabla
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 68
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 82
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Sonarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxyCache(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 70
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 60
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 435
blabla
----
При этом не важно как ты ломишься в qbit - через имя сервиса в докере или делаешь петлю через бридж на хостовой оси (192.168.2.10 в моем случае)
но прикол в том, что если использовать тип сети "хост" у контейнера, то это говно просто работает.

=== ручной импорт
Если ты затупил и не поставил нужную категорию на торренте в qbit, то ее установка на "нужную" уже после завершения скачивания не поможет, файлы не будет видно в Activity Menu.
Но зато, если переключиться в Wanted → Missing, то можно выделить серии которые ожидаются к загрузке в sonarr и сделать Manual Import, указав каталог, в который была загрузка.

include::plex/plex-configure.adoc[]

=== youtube
В последнее время в качестве движка стоит использовать форк 
yt-dlp из-за таких опций, как:

- скачать из специального плейлиста
- запоминание скачанного
- использование временного интервала для пересканирования плейлиста для сохранения

==== Atls
Альтернативы - зачахли. А вот c UI есть определенный геморой

===== Alt1
среди альтернатив выделяется https://github.com/Jeeaaasus/youtube-dl из-за таких опций, как:

- скачать из специального плейлиста
- запоминание скачанного
- использование временного интервала для пересканирования плейлиста для сохранения


Но вот UI как такового нет, все указывается в 2 файлах.
При этом 1 это веб морда Portainer с yaml редактором конфигурации.

А второй это 2 таба терминала с открытыми Vim. Ну прямо не очень то и удобно.

===== Alt2
https://github.com/timendum/Youtube-dl-WebUI
Простенькая морда, многое можно указать в полях ввода, немного простовата
Можно собрать его докер билдом самостоятельно, но.. страно что чувак не готов поставлять образы.
Не удобно будет протаскивать в Portainer.

===== Alt3
https://github.com/alexta69/metube
Простая морда с предустановленными пресетами.
Есть проблема с частыми релизами yt-dpl - придется часто обновлять контейнер. Для этого рекомендуют поставить https://github.com/containrrr/watchtower и даже настрогали
https://www.reddit.com/r/synology/comments/pzu4oy/comment/hf42m98/?utm_source=share&utm_medium=web2x&context=3[видеомануал]
Черех UI только интерфейс указания url видео для скачивания.
Все остальное настраивается через docker env переменные.
В том числе будет огромная YTDL_OPTIONS которую читать и править будет очень не удобно.
Но разок и можно.

===== Alt4
Чуть сложнее и заковыристиее проект https://hub.docker.com/r/whatdaybob/sonarr_youtubedl
Он пытается раскладывать видосы с каналов так же, как это делает сонарр.
Теже ключевые опции присутсвуют, настройка заставит попыхтеть над файлом конфигурации https://github.com/whatdaybob/sonarr_youtubedl/blob/main/app/config.yml.template.

=== jellyfrin
Первые приколы начинаются с декодирования. Так как у меня старый камень, то нужно поставить не сводобные драйвера `apt update && apt install intel-media-va-driver` и запросить диагностичесую информацию командой `vainfo`. Вот мой вывод
[source,txt]
----
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
---- 

А в опциях декодирования нужно выбрать не QSV a VAAPI
и проставить аппаратное ускорение только у
✅ H264 (VAProfileH264)
✅ MPEG2 (VAProfileMPEG2)
✅ VC1 (VAProfileVC1*)

Продолжаются приколы работой опции trickplay. jellyfrin разросся и решил сделать ускоренную перемоку, и для этого ffmpeg'ом выковырывает спрайты из видеофайлов. Это было бы удобно, если пользоваться просмотром в нем на постоянной основе. Но на первом месте у меня dlna, что бы не иметь проблем с транскодированием на древнем камне. А в dlna обозревать лишние каталоги и спрайты - нафиг не надо. По сему эта опция откллючена в каждой библотеке.
