---
# name: xray-client
services:
    xray:
      build:
        context: .
        # dockerfile: v2raya.Dockerfile
        dockerfile_inline: |
          FROM mzz2017/v2raya:latest
          RUN \
            wget -O /usr/local/share/v2ray/geosite.dat \
            https://github.com/1andrevich/Re-filter-lists/releases/latest/download/geosite.dat && \
            wget -O /usr/local/share/v2ray/geoip.dat \
            https://github.com/1andrevich/Re-filter-lists/releases/latest/download/geoip.dat
          ENTRYPOINT ["v2raya"]
      container_name: proxyd
      volumes:
      - /lib/modules:/lib/modules:ro
      - ./v2raya:/etc/v2raya
      ports:
        - 2017:2017 # web configuration
        - 20170-20172:20170-20172 # inbound and ounboud ports
      environment:
        V2RAYA_NFTABLES_SUPPORT: on
      privileged: true
      networks:
        jumper2kamartaj:
        elder_ip_subnet_type_c:
          ipv4_address: ${IP_XRAY}
          mac_address: ${MAC_XRAY}
      restart: unless-stopped

networks:
  jumper2kamartaj:
    external: true
  elder_ip_subnet_type_c:
    external: true