:toc: left
== net-mod

=== xray
Начал присматривать замену torproxy и требовался какой-нибудь клиент, что бы контейнерам указывать обычную проксю. 

Для начала нужно проверить какой у нас сейчас ip через `curl http://httpbin.org/get`, должно вывоподиться что то вроде

[source,json]
----
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/8.10.1",
    "X-Amzn-Trace-Id": "Root=1-67733b03-71a0ab3b2102d1c06d23009a"
  },
  "origin": "46.138.21.92",
  "url": "http://httpbin.org/get"
}
----


Потом ваш url подключения нужно распарсить и привести в json виду с помощью проектов 

- https://github.com/ImanSeyed/v2ray-uri2json
- https://github.com/Am-Delta/v2ray-to-json

Мержить нужно будет глазками, есть незначительные отличия.

Теперь про проекты.

Есть странный косой докер образ https://github.com/samuelhbne/proxy-xray?tab=readme-ov-file
В принципе он поддерживает все что нужно, но нужно руками задавать все параметры подключения в компоуз. Это можно, но не удобно.

А есть https://github.com/v2rayA/v2rayA , который встрает даже на роутеры https://habr.com/ru/articles/773696/.
Но мы то будем использовать https://v2raya.org/en/docs/prologue/installation/docker/

Берем `docker-compose -f docker-compose-vless.yaml up` и пользуемся.
Если что то переделали под себя то `docker-compose -f docker-compose-vless.yaml up --build`

В консоли будет приглашение открыть веб интерфейс, не стеняемся и задаем логин и пароль.

Теперь надо пробежаться по разделам конфигурации.

Transparent Proxy/System Proxy → 
On: Traffic Splitting Mode is the Same as the Rule Port 

IP Forwarding = true
Port Shating = true

Traffic Splitting Mode of Rule Port → 
RoutingA → 
copy config
[source,text]
----
default: proxy
# write your own rules below
ip(geoip:refilter)->proxy
domain(ext:"geosite.dat:refilter")->proxy
----

Prevent DNS Spoofing → 
Advanced Setting →
copy config
[source,text]
----
https://dns.alidns.com/dns-query -> direct
tcp://dns.opendns.com:5353 -> proxy
119.29.29.29 -> direct
----

и САМОЕ главное, если строчка с удаленным сервером горит красным, то вы его просто протестировали, но не подключили.
Включить соединение нужно по кнопке слева сверху, чуть правее иконки v2raya

По завершению настройки нужно вызывать `curl -sx 127.0.0.1:20170 http://httpbin.org/get` и ip адрет будет уже другой. Если нужен галимый http прокси, то там будет дефолтный порт рядом 20171

По завершению настройки нужно вызывать `curl -sx 127.0.0.1:20170 http://httpbin.org/get` и ip будет уже другой. Если нужен галимый http прокси, то там будет дефолтный порт рядом 20171

Там есть некоторые неудобства с обновлением образа из-за кастомного докербилда с принудительным выкачиванием нужных дат файлов. И подписки не умеет. Но куда большая проблема - v2raya заколебал. По этому он отправляется в архив.

=== 3x-ui
Есть конечно https://github.com/MHSanaei/3x-ui
Но он не обновляет по

=== shadowsocks

Гугл подсказывает, что среди прочих альтернатив для ss2022 стоит посмотреть на https://github.com/shadowsocks/shadowsocks-hub

Этим ребятам уперлось сделать подключение только по ssl, так что придется пробрасывать ключи. А это не удобно.

=== mihomo
https://github.com/MetaCubeX/mihomo/ на самом деле не то чем кажется :)
Но там очень долго можно курить мануал https://wiki.metacubex.one/en/config/general/, для погружения проще воспользоваться генераторами

 - https://github.com/raywari/mihomo-constructor
 - https://generator.rockblack.pro/

Генераторы могут наделать всякого, так что как минимум стоит проверить выставленные порты `sudo ss -tlnp | grep LISTEN`

Но лучше воспользоваться состряпанным универсальным link:cfg.mih.uni.yml[конфигом],
который будет расширяться конфигом для link:cfg.mih.nas.yml[NAS] 
или для link:cfg.mih.cell.yml[мобилы]


Основная проблема в расширении/слиянии: после того как git-sync отработал слияние через https://hub.docker.com/r/mikefarah/yq просходит только один раз. Да еще и с проблемами на владение файлов. Там такие инлайн башизмы приходится городить - закачаешься.
Но можно воспользоваться https://github.com/mcgr0g/clash-cfg-mixer он решает все проблемы. А пример подключения в https://github.com/mcgr0g/clash-cfg-mixer/blob/main/docker-compose.yml
Ребятам из linuxserver нужно респектнуть за мод https://github.com/linuxserver/docker-mods/tree/universal-package-install через который можно поставить всякое в пару к богомерзкому s6-overlay

=== b4
Тут появился https://daniellavrushin.github.io/b4/docs/intro[b4]
Можно выставить свой порт для socks5 сервера. Надо будет потрогать и поставить в пару с mihomo. Главное не давать им обоим доступ в хостовые iptables, оба будут конкурировать за них.