version: "3.8"
services:

  organizr:
    image: ghcr.io/organizr/organizr # https://github.com/organizr/docker-organizr
    container_name: organizr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${ROOT}/configs/organizr:/config
    ports:
      - 8888:80
    restart: unless-stopped

  torrserver:
    container_name: torrserver # https://github.com/YouROK/TorrServer
    image: ghcr.io/yourok/torrserver:latest 
    hostname: torrserver
    domainname: torrserver.lan
    volumes:
      - '${ROOT}/configs/ts:/opt/ts/config'
      - '${ROOT}/cache/torrserver:/opt/ts/torrents'
    ports:
      - 8090:8090 # http streaming
      - 1900:1900 # dlna discover
      - 1338:1338 # dlna default streaming port https://github.com/anacrolix/dms/blob/master/README.rst#usage-of-dms
    networks:
      mcvlan_subnet:
        ipv4_address: 192.168.1.230
    restart: unless-stopped

  qbittorrent: # https://github.com/linuxserver/docker-qbittorrent
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      WEBUI_PORT: 8080
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${ROOT}/configs/qbittorrent:/config
      - ${ROOT}/media/torrents:/media/torrents
      - ${ROOT}/yandex/blackhole:/blackhole
    ports:
      - 6881:6881 # tcp connection port
      - 6881:6881/udp # udp connection port
      - 8080:8080 # http gui
    restart: unless-stopped

  torproxy:
    container_name: torproxy
    image: mcgr0g/talpa-altaica:latest
    environment:
     EXCLUDE_NODE: '{RU},{UA},{AM},{KG},{BY}'
    ports:
    - 8118:8888 # подмена порта из-за коллизии
    - 8119:8889
    - 9050:9050/tcp
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      # RUN_OPTS: --ProxyConnection=torproxy:8118
      PUID: ${PUID} # default user id, defined in .env
      PGID: ${PGID} # default group id, defined in .env
      TZ: ${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/configs/jackett:/config # config files
      - ${ROOT}/yandex/blackhole:/downloads # place where to put .torrent files for manual download
    ports:
      - 9117:9117
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped 

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    network_mode: host
    environment:
      PUID: ${PUID} # default user id, defined in .env
      PGID: ${PGID} # default group id, defined in .env
      TZ: ${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/configs/sonarr:/config # config files
      - ${ROOT}/media:/media # both downloads & media folders folder
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    network_mode: host
    environment:
      PUID: ${PUID} # default user id, defined in .env
      PGID: ${PGID} # default group id, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/configs/radarr:/config # config files
      - ${ROOT}/media:/media # both downloads & media folders folder
    ports:
      - 7878:7878
    restart: unless-stopped

networks: 
  mcvlan_subnet:
    name: elder_ip_subnet_type_c
    driver: macvlan
    driver_opts:
      parent: br0 # если вместо физической карты настроен бридж, то нужно указывать именно его
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.2
          ip_range: 192.168.1.224/27