:toc: left
== media-box

=== references
Наработки взяты из мануалов

- https://github.com/sebgl/htpc-download-box
- https://creio.github.io/media-server/
- https://connect.smartliving.ru/profile/225/blog/ustanovka-i-nastroyka-sonarr-radarr-qbittorrent-jackett-torproxy-v-docker.html
- https://habr.com/ru/post/428992/

[[qbit]]
=== torrent client
Театр начинается именно с этой вешалки https://github.com/linuxserver/docker-qbittorrent
(хотя есть и https://hotio.dev/containers/qbittorrent/[альтернативные] сборки )

Вообще все остальное выстраивать относительно `/media/torrents/`
например назначить скачивание в `/media/torrents/downloads`
а конкретные категории, такие как radarr назначить в `/media/torrents/movies`

каталог для мониторинга торрент файлов стоит назначить как `/media/torrents/blackhole`. В него можно настроить перекладывание .torrent файлов по крону.

для отладки смотрим что происходит внутри `sudo docker exec -it qbittorrent bash`

==== анонсеры
стоит сразу же добавить список ретрекеров https://github.com/ngosang/trackerslist
в ⚙ → BitTorrent → Automatically add these trackers to new downloads

для проверки аптайма анонсера можно воспользоваться https://newtrackon.com/

Скорее всего большая часть будет заблокирована, стоит использовать https://github.com/bluet/proxybroker2

==== TorrServer 
Проект https://github.com/YouROK/TorrServer работает даже на android боксах. Если телеков несколько, а сервер один, можно сэкономить, стримить телекам контент по dlna.

Можно нацеливать хранение кеша на пзу в `/opt/ts/torrents/`. Этот каталог пробрасывается в хост систему.
```
sudo docker exec -it torrserver sh
ls -la /opt/ts/
```
При этом там только кэш, который ничем сторонним прочитать нельзя, так что располагать его в структуре smb или dlna шары - не надо.

Там же в конфигах можно включить опцию dlna шары и она будет стримить выбранный торрент файл.
В компоузе специально проброшены порты для этого. А что бы не было коллизии портов, ТS отселен на отдельный ip.

=== tor
Потребуется для доступа к заблокированному контенту, torrent трекерам, ретрекерам, а нынче еще и для доступа к серверам sonarr и radarr
Есть классные сборки образов

- https://github.com/binfalse/docker-tor
- https://github.com/datawookie/docker-tor-privoxy

но ни в одной нет проброса env'а ExcludeExitNodes.
Пришлось https://github.com/mcgr0g/tor-privoxy[подшаманить] самому.

Главная опция: ExcludeExitNodes {RU},{UA},{AM},{KG},{BY}

Бесполезно использовать для торрент траффика, для этого уже нужно покупать vpn.

=== organizers
И sonarr и radarr нужно скормить одни и теже индексаторы, одни и теже качалки, каталоги.
Об этом всем подробнее в мануале https://wiki.servarr.com/docker-guide#sonarr-radarr-and-lidarr
потребуется часто переключаться между приложениями, а можно настроить дашборт с jump-кнопками и текущими статусами очередей задач. Для этого пригодится https://github.com/organizr/docker-organizr

Установка не замысловатая. Настраивается по мере ввода в эксплуатацию нового приклада.

[[torrent-indexer]]
=== Jackett
Он не сможет работать в наших реалиях без tor и flaresolverr. При дефолтных настройках контейнеров, нужно в UI прописать 

- FlareSolverr API URL: `http://flaresolverr:8191`
- Proxy URL: `192.168.1.10` # torproxy ip
- Proxy port: `9050` # torproxy direct port
- FlareSolverr Max Timeout (ms): `105000` из-за неторопливости tor

при добавлении индексатора на больших форумах могут возникнуть проблемы. Стоит предварительно поискать ваши любимые фильмы и сериалы на форуме, запомнить человекочитаемые категории. А потом в интерфейсе жакета через ctrl+f найти соответствующие им тэги.

Например у рутрекера получился такой набор тэгов

[%autowidth%header,separator=|]
|===
| тэг | назначение 

| 2040
| Movies/HD

| 2045
| Movies/UHD

| 2070
| Movies/DVD

| 101457
| UHD Video

| 102294
| UHDTV

| 100313
| Зарубежное кино (HD Video)

| 100101
| Зарубежное кино (DVD Video)

| 100119
| Зарубежные сериалы (UHD Video)

| 101803
| Новинки и сериалы в стадии показа (HD Video)

| 102366
| Зарубежные сериалы (HD Video)

| 100920
| Русские сериалы (DVD Video)

| 100081
| Русские сериалы (HD Video)

| 100312
| Наше кино (HD Video)

| 102164
| BBC, Discovery, National Geographic, History Channel (HD Video)

|===

=== radarr
качает фильмы
сначала надо сделать приседание с регистрацией и получения идентификатора своего листа к просмотру

[[list-id]]
==== imdb
Важно айдишник, начинающийся на ur - это id пользователя.
id списка начинается на ul. Как его получить?
Идете на свой профиль вида `https://www.imdb.com/user/ur123/watchlist`
На странице ищите `Export this list`
Под текстом будет ссылка, содержащая id листа.

Дальше надо скормить идентификатор серверу.

==== Root Folders
в Settings  → Root Folders → Path указываете путь вида `/media/ready/movies`
Это каталог в проброшенном volume в докер. Будет использоваться для красивого раскладывания фильмов, описания и аротов, что бы их скушал plex или jellyfin
Если использовалась структура каталогов из этого проекта, то раскладывание будет осуществляться с помощью хардлинков, нацеленных на каталог qbittorent.

==== Profiles
Нужно в каждом профиле поставить русский язык

==== General
в Settings → General → Proxy указываете параметры подключения к контейнеру с тор. Иначе не заработает.
Так как я не отковыривал torproxy в отдельный ip (см приложенный compose), мои конфиги были
SOCKS5, localhost, 9050

==== Download Clients
в Settings → Download Clients добавляте qBittorrent с параметрами

- Host: localhost
- Port: 8080 (или что там у вас в compose)
- Username: <ваш сконфигуренный пользователь в клиенте>
- Password
- Category: radarr (ее уже настроили в разделе [<<qbit>>])

==== Lists
в Settings → Lists добавляте новый список с типом `IMDb List`. Там конфигурируетe

- Quality Profile: например в 1080p
- Folder: /media/ready/moovies
- List/User ID: ваш список просмотра из [<<list-id>>]

Если немного подождать или попинать интерфес в Moovies → Update all, то
сервер через torproxy пойдет сначала в imdb и потом создаст каталоги и метаданные фильмов

===== Indexers
в Settings → Indexers добавляете torrent индексы c стипом `Torznab`
и для каждого настроенного торрент трекера/форума в [<<torrent-indexer>>] копируете tornzab и api-key и вставляете в модалке
- URL: `http://localhost:9117/api/v2.0/indexers/rutor/results/torznab/`
- API Key: ну вы поняли

Categories - следует выделить только те категории с трекера, которые вам интересны. Например на рутрекере есть куча разделов под всякую музыку, софт и прочее барахло, которое нет смысла процессить.

Сам процессинг при этом может иногда сыпать ошибками в System → Events.
Это связано с тем, что torproxy переключается между выходными нодами и переключение может совпасть с моментом опроса новинок.


=== sonarr
Качает сериалы. Настраивается аналогично, но сериалы добавляются руками, а не через какой-нибудь внешний список к просмотру.
