:toc: left
:toclevels: 4
== media-box

=== references
Наработки взяты из мануалов

- https://github.com/sebgl/htpc-download-box
- https://creio.github.io/media-server/
- https://connect.smartliving.ru/profile/225/blog/ustanovka-i-nastroyka-sonarr-radarr-qbittorrent-jackett-torproxy-v-docker.html
- https://habr.com/ru/post/428992/

[[qbit]]
=== torrent client
Театр начинается именно с этой вешалки https://github.com/linuxserver/docker-qbittorrent
(хотя есть и https://hotio.dev/containers/qbittorrent/[альтернативные] сборки )

Не смотря на то, что мануалы сонара рекомендуют монировать контейнер как `${ROOT}/media/torrents:/media/torrents`, рекомендую монтировать как `${ROOT}/media:/media`. Причина простая: сонар, да и радар плохо умеет сам искать и сопоставлять русские заголовки. Особенно плохо ему делается при попытках найти какой-нибудь весь пак старого сериала. Тогда приходится руками выкачивать в каталог сонара. Тут то и нужен доступ в его каталоги.

Все остальное для штатного использования рекомендуется выстраивать относительно `/media/torrents/`.

Каталог для мониторинга торрент файлов стоит назначить как `/media/torrents/blackhole`. В него можно настроить перекладывание .torrent файлов по крону.

Для отладки смотрим что происходит внутри `sudo docker exec -it qbittorrent bash`

==== Категории
Например, скачивание по умолчанию без категорий можно назначить скачивание в `/media/torrents/downloads`
Можно задать "пустую категорию", тогда скачивание пойдет в `/media/torrents/downloads/categoryName`.

Однако удобнее всего пользоваться подготовленными категориями вида
moovie = '/media/torrents/movies'
serial = '/media/torrents/serial'
radarr = '/media/torrents/movies'

Хак с отдельной категорией для радара и сонара упрощает жизнь в реалиях отчечественных трекеров. 
В PVR можно настроить категорию для скачивания и пост категорию для готового фильма. При этом фильм не будет считаться готовым, если PVR не смог его сграбить автоматом. А один чудный трекер постоянно отдает в названии торрента "rutor.info" вместо имени темы или названия файла. И radarr имено так его и показыват в своем интерфейс для импорта контента. По этому каждый раз в интерфейсе qbit приходится править название торрента по имени файлу руками. И гораздо проще найти это непотребство фильтранувшись по категории.

==== анонсеры
Стоит сразу же добавить список ретрекеров https://github.com/ngosang/trackerslist
в ⚙ → BitTorrent → Automatically add these trackers to new downloads

для проверки аптайма анонсера можно воспользоваться https://newtrackon.com/

Скорее всего большая часть будет заблокирована, стоит использовать https://github.com/bluet/proxybroker2

=== TorrServer 
Проект https://github.com/YouROK/TorrServer работает даже на android боксах. 
Если телеков несколько, а сервер один, можно сэкономить на wifi траффике, стримить телекам контент по dlna.
Если вы собираете проект под amd64, стоит нацеливать хранение кеша на пзу в `/opt/ts/torrents/`. Этот каталог пробрасывается в хост систему. И проверьте что он создается именно там, запустим торрент и провалившись в контейнер
```
sudo docker exec -it torrserver sh
ls -la /opt/ts/
```
При этом там только кэш, который ничем сторонним прочитать нельзя, так что располагать его в структуре smb или dlna шары - бессмысленно.

Если вы зачем то делаете это на rpi, то взаимодействие с диском у вас будет так себе, нужно оставить дефолтный конфиг с записью в ram.

Там же в конфигах можно включить опцию dlna шары и она будет стримить выбранный торрент файл.
Сделав этот выбор, контейнер придется перенести в сеть маклана на отдельный ip, что бы не было коллизии портов с baremetal dlna сервером. 

Зачем? Онлайн стриминг это конечно хорошо, но локальне файлы должны быть доступны всегда и по самому бородатому протоколу. 


=== torproxy
Потребуется для доступа к заблокированному контенту, torrent трекерам, ретрекерам, а нынче еще и для доступа к серверам sonarr и radarr
Есть классные сборки образов

- https://github.com/binfalse/docker-tor
- https://github.com/datawookie/docker-tor-privoxy

но ни в одной нет проброса env'а ExcludeExitNodes.
Пришлось https://github.com/mcgr0g/tor-privoxy[подшаманить] самому.

Главная опция: ExcludeExitNodes {RU},{UA},{AM},{KG},{BY}

Бесполезно использовать для торрент траффика, для этого уже нужно покупать vpn.

=== organizers
И sonarr и radarr нужно скормить одни и теже индексаторы, одни и теже качалки, каталоги.
Об этом всем подробнее в мануале https://wiki.servarr.com/docker-guide#sonarr-radarr-and-lidarr
И в процессе постоянного тюнинга потребуется часто переключаться между приложениями.
А  можно настроить дашборт с jump-кнопками и текущими статусами очередей задач. Для этого пригодится https://github.com/organizr/docker-organizr

Установка не замысловатая. Настраивается по мере ввода в эксплуатацию нового приклада.

[[torrent-indexer]]
=== Jackett
Он не сможет работать в наших реалиях без flaresolverr и tor (а лучше VPN). 
При этом скорость взаимодействия будет очень медленной. Так что для первичного запуска стоит воспользоваться torproxy, а потом тюнить конфиги для более быстрого соединения через vpn туннель.
При дефолтных настройках контейнеров,

```docker
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      PUID: ${PUID} # default user id, defined in .env
      PGID: ${PGID} # default group id, defined in .env
      TZ: ${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/configs/jackett:/config # config files
      - ${ROOT}/yandex/blackhole:/downloads # place where to put .torrent files for manual download
    ports:
      - 9117:9117
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: ${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped 
```
нужно в UI прописать 

- Proxy type: SOCKS5 // подключение на прямую к tor клиенту сети
- Proxy URL: `torproxy` // при взаимодействии в докер сети за бриджом хосты будут резолвиться по имени сервиса
- Proxy port: `9050` # torproxy direct port
- FlareSolverr API URL: `http://flaresolverr:8191`
- FlareSolverr Max Timeout (ms): `105000` из-за неторопливости tor

После добавления любимых трекеров стоит их протестировать и поискать какие-нибудь новинки. Если все отлично, то на этом стадия первичного запуска считается завершенной.

=== radarr
качает фильмы
сначала надо сделать приседание с регистрацией и получения идентификатора своего листа к просмотру

[[list-id]]
==== imdb 
Важно айдишник, начинающийся на ur - это id пользователя.
id списка начинается на ul. Как его получить?
Идете на свой профиль вида `https://www.imdb.com/user/ur123/watchlist`
На странице ищите `Export this list`
Под текстом будет ссылка, содержащая id листа.

Дальше надо скормить идентификатор серверу.

==== Root Folders
в Settings  → Root Folders → Path указываете путь вида `/media/ready/movies`
Это каталог в проброшенном volume в докер. Будет использоваться для красивого раскладывания фильмов, описания и аротов, что бы их скушал plex или jellyfin
Если использовалась структура каталогов из этого проекта, то раскладывание будет осуществляться с помощью хардлинков, нацеленных на каталог qbittorent.

==== Profiles
Нужно в каждом профиле поставить русский язык

==== General
в Settings → General → Proxy указываете параметры подключения к контейнеру с тор. Иначе не заработает.
Так как я не отковыривал torproxy в отдельный ip (см приложенный compose), мои конфиги были
SOCKS5, localhost, 9050

==== Download Clients
в Settings → Download Clients добавляте qBittorrent с параметрами

- Host: localhost
- Port: 8080
- Username: <ваш сконфигуренный пользователь в клиенте>
- Password
- Category: radarr (ее уже настроили в разделе [<<qbit>>], о ней подборнее будет ниже)

==== Lists
в Settings → Lists добавляте новый список с типом `IMDb List`. Там конфигурируетe

- Quality Profile: например в 1080p
- Folder: /media/ready/moovies
- List/User ID: ваш список просмотра из [<<list-id>>]

Если немного подождать или попинать интерфес в Moovies → Update all, то
сервер через torproxy пойдет сначала в imdb и потом создаст каталоги и метаданные фильмов

===== Indexers
в Settings → Indexers добавляете torrent индексы c стипом `Torznab`
и для каждого настроенного торрент трекера/форума в [<<torrent-indexer>>] копируете tornzab и api-key и вставляете в модалке
- URL: `http://localhost:9117/api/v2.0/indexers/rutor/results/torznab/`
- API Key: ну вы поняли

====== Categories
Следует выделить только те категории с трекера, которые вам интересны. Например на рутрекере есть куча разделов под всякую музыку, софт и прочее барахло, которое нет смысла процессить.

Пример тэгов (не системных для всего радара, а только для индексатора), которые были полезны мне

[%autowidth%header,separator=|]
|===
| тэг | назначение 

| 2040
| Movies/HD

| 2045
| Movies/UHD

| 2070
| Movies/DVD

| 101457
| UHD Video

| 102294
| UHDTV

| 100004
| Мультфильмы

| 100313
| Зарубежное кино (HD Video)

| 100119
| Зарубежные сериалы (UHD Video)

| 101803
| Новинки и сериалы в стадии показа (HD Video)

| 102366
| Зарубежные сериалы (HD Video)

| 100920
| Русские сериалы (DVD Video)

| 100081
| Русские сериалы (HD Video)

| 100312
| Наше кино (HD Video)

| 102164
| BBC, Discovery, National Geographic, History Channel (HD Video)

|===

Сам процессинг при этом может иногда сыпать ошибками в System → Events.
Это связано с тем, что torproxy переключается между выходными нодами и переключение может совпасть с моментом опроса новинок.

===== manual import
У многих не ищутся фильмы из-за кривых локализованных заголовковов фильмов 
или из-за разных дат релиза в мире (был один год), и в стране релиза (часто следующий).

И при том разработчики умышленно не дают пофиксить заголовки, говорят идти на tvdb и фиксить там.
Я пробовал, это так не работает.
Но есть обходной маневр: руками через jacket найти нужный фильм, скачать torrent файл, а при добавлении его в <<qbit>> поставить категорию radarr.
Тогда сервис заметит его в попытается сграбить. Даже если у него не получится, то можно ему подмогнуть через Grab selected

=== sonarr
Качает сериалы. Настраивается аналогично, но сериалы добавляются руками, а не через какой-нибудь внешний список к просмотру.


include::plex/plex-configure.adoc[]

=== youtube
В последнее время в качестве движка стоит использовать форк 
yt-dlp из-за таких опций, как:

- скачать из специального плейлиста
- запоминание скачанного
- использование временного интервала для пересканирования плейлиста для сохранения

==== Atls
Альтернативы - зачахли. А вот c UI есть определенный геморой

===== Alt1
среди альтернатив выделяется https://github.com/Jeeaaasus/youtube-dl из-за таких опций, как:

- скачать из специального плейлиста
- запоминание скачанного
- использование временного интервала для пересканирования плейлиста для сохранения


Но вот UI как такового нет, все указывается в 2 файлах.
При этом 1 это веб морда Portainer с yaml редактором конфигурации.

А второй это 2 таба терминала с открытыми Vim. Ну прямо не очень то и удобно.

===== Alt2
https://github.com/timendum/Youtube-dl-WebUI
Простенькая морда, многое можно указать в полях ввода, немного простовата
Можно собрать его докер билдом самостоятельно, но.. страно что чувак не готов поставлять образы.
Не удобно будет протаскивать в Portainer.

===== Alt3
https://github.com/alexta69/metube
Простая морда с предустановленными пресетами.
Есть проблема с частыми релизами yt-dpl - придется часто обновлять контейнер. Для этого рекомендуют поставить https://github.com/containrrr/watchtower и даже настрогали
https://www.reddit.com/r/synology/comments/pzu4oy/comment/hf42m98/?utm_source=share&utm_medium=web2x&context=3[видеомануал]
Черех UI только интерфейс указания url видео для скачивания.
Все остальное настраивается через docker env переменные.
В том числе будет огромная YTDL_OPTIONS которую читать и править будет очень не удобно.
Но разок и можно.

===== Alt4
Чуть сложнее и заковыристиее проект https://hub.docker.com/r/whatdaybob/sonarr_youtubedl
Он пытается раскладывать видосы с каналов так же, как это делает сонарр.
Теже ключевые опции присутсвуют, настройка заставит попыхтеть над файлом конфигурации https://github.com/whatdaybob/sonarr_youtubedl/blob/main/app/config.yml.template.
