:toc: left
== media-box

=== references
Наработки взяты из мануалов

- https://github.com/sebgl/htpc-download-box
- https://creio.github.io/media-server/
- https://connect.smartliving.ru/profile/225/blog/ustanovka-i-nastroyka-sonarr-radarr-qbittorrent-jackett-torproxy-v-docker.html
- https://habr.com/ru/post/428992/


=== torrent client
Театр начинается именно с этой вешалки https://github.com/linuxserver/docker-qbittorrent
(хотя есть и https://hotio.dev/containers/qbittorrent/[альтернативные] сборки )

Вообще все остальное выстраивать относительно `/media/torrents/`
например назначить скачивание в `/media/torrents/downloads`
а конкретные категории, такие как radarr назначить в `/media/torrents/movies`

каталог для мониторинга торрент файлов стоит назначить как `/media/torrents/blackhole`. В него можно настроить перекладывание .torrent файлов по крону.

для отладки смотрим что происходит внутри `sudo docker exec -it qbittorrent bash`

==== анонсеры
стоит сразу же добавить список ретрекеров https://github.com/ngosang/trackerslist
в ⚙ → BitTorrent → Automatically add these trackers to new downloads

для проверки аптайма анонсера можно воспользоваться https://newtrackon.com/

Скорее всего большая часть будет заблокирована, стоит использовать https://github.com/bluet/proxybroker2

==== TorrServer 
Проект https://github.com/YouROK/TorrServer работает даже на android боксах. Если телеков несколько, а сервер один, можно сэкономить, стримить телекам контент по dlna.

Можно нацеливтаь хранения кеша на пзу в `/opt/ts/torrents/` именно туда, потому что это каталог пробрасывается в хост систему.
```
sudo docker exec -it torrserver sh
ls -la /opt/ts/
```
При этом там только кэш, который ничем сторонним прочитать нельзя, так что располагать его в структуре smb или dlna шары - не надо.

=== Organizers
И sonarr и radarr нужно скормить корневой каталог, что бы они смогли расставлять хардлинки между разными каталогами подробнее в мануале https://wiki.servarr.com/docker-guide#sonarr-radarr-and-lidarr

=== tor
Потребуется для доступа к заблокированному контенту, torrent трекерам, ретрекерам, а нынче еще и для доступа к серверам sonarr и radarr
Есть классные сборки образов

- https://github.com/binfalse/docker-tor
- https://github.com/datawookie/docker-tor-privoxy

но ни в одной нет проброса env'а ExcludeExitNodes.
Пришлось https://github.com/mcgr0g/tor-privoxy[подшаманить] самому.

Главная опция: ExcludeExitNodes {RU},{UA},{AM},{KG},{BY}

Бесполезно использовать для торрент траффика, для этого уже нужно покупать vpn.

=== Jackett
Он не сможет работать в наших реалиях без tor и flaresolverr. При дефолтных настройках контейнеров, нужно в UI прописать 

- FlareSolverr API URL: `http://flaresolverr:8191`
- Proxy URL: `192.168.1.10` # host ip
- Proxy port: `8118` # squid port
- FlareSolverr Max Timeout (ms): `105000` из-за нетопропливости tor

при добавлении индексатора на больших форумах могут возникнуть проблемы. Стоит предварительно поискать ваши любимые фильмы и сериалы на форуме, запомнить человекочитаемые категории. А потом в интрефейсе жакета через ctrl+f найти соответствующие им тэги.

Например у рутрекера получился такой набор тэгов

[%autowidth%header,separator=|]
|===
| тэг | назначение 

| 2040
| Movies/HD

| 2045
| Movies/UHD

| 2070
| Movies/DVD

| 101457
| UHD Video

| 102294
| UHDTV

| 100313
| Зарубежное кино (HD Video)

| 100101
| Зарубежное кино (DVD Video)

| 100119
| Зарубежные сериалы (UHD Video)

| 101803
| Новинки и сериалы в стадии показа (HD Video)

| 102366
| Зарубежные сериалы (HD Video)

| 100920
| Русские сериалы (DVD Video)

| 100081
| Русские сериалы (HD Video)

| 100312
| Наше кино (HD Video)

| 102164
| BBC, Discovery, National Geographic, History Channel (HD Video)

|===
